language: cpp
dist: trusty
sudo: required

matrix:
  include:
    - compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
      env:
        - MATRIX_EVAL="CXX=g++-7"
    - compiler: clang++
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - cmake
      env:
        - MATRIX_EVAL="CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo add-apt-repository -s -y 'deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse'

before_script:
  - sudo apt-get update
  - sudo apt-get install -y libboost-all-dev
  - sudo apt-get install -y liblapacke-dev
  - sudo apt-get install -y libeigen3-dev
  - sudo apt-get install -y libboost-program-options-dev
  - sudo apt-get install -y libboost-log-dev
  - sudo apt-get install -y libboost-system-dev
  - mkdir build
  - cd build
  - echo "the CXX compiler for cmake is $CXX"
  - cmake ../ -DCMAKE_CXX_COMPILER=${CXX}

script:
  - pwd
  - make && make test