language: cpp
dist: trusty
sudo: required

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
      env:
        - MATRIX_EVAL="CXX=g++-5"
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.8
            - g++-5
            - cmake
      env:
        - MATRIX_EVAL="CXX=clang++-3.8"
before_install:
    - eval "${MATRIX_EVAL}"
    - sudo add-apt-repository -s -y 'deb http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse'

before_script:
  - sudo apt-get update
  - sudo apt-get install -y libboost-all-dev liblapacke-dev
  - mkdir build
  - cd build
  - echo "the CXX compiler for cmake is $CXX"
  - cmake ../ -DCMAKE_CXX_COMPILER=${CXX} -D_GLIBCXX_USE_CXX11_ABI=0

script:
  - pwd
  - make
  - make test